[versions]
telegrambots = "7.9.1"
snakeyaml = "2.2"

[libraries]
telegrambots-longpolling = { module = "org.telegram:telegrambots-longpolling", version.ref = "telegrambots" }
telegrambots-client = { module = "org.telegram:telegrambots-client", version.ref = "telegrambots" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
